export type PhraseContext =
  | 'ordinary'
  | 'complex'
  | 'functions'
  | 'nesting'
  | 'repeat'
  | 'zero'
  | 'negative'
  | 'huge'
  | 'tiny'
  | 'syntax'
  | 'math_error'
  | 'division_zero'
  | 'domain'
  | 'recovery'
  | 'philosophy'
  | 'hype';

export type CommentaryPhrase = {
  id: string;
  contexts: readonly PhraseContext[];
  ru: string;
  en: string;
};

// Success contexts describe accepted results. Shared math_error phrases make no
// parser, domain or result-size claims, so they also fit other accepted errors.
export const PHRASE_CATALOG: readonly CommentaryPhrase[] = [
  { id: 'answer_receipt_a', contexts: ['ordinary'], ru: 'Ответ готов. Чек не нужен.', en: 'Answer ready. No receipt needed.' },
  { id: 'equals_shift_a', contexts: ['ordinary'], ru: 'Знак равенства закончил смену.', en: 'The equals sign has clocked out.' },
  { id: 'number_pocket_a', contexts: ['ordinary'], ru: 'Вот число. Помещается в карман.', en: 'Here’s a number. Pocket-sized.' },
  { id: 'answer_signature_a', contexts: ['ordinary'], ru: 'Результат можно забрать без подписи.', en: 'You can collect the result without signing.' },
  { id: 'expression_answered_a', contexts: ['ordinary'], ru: 'Выражение получило ответ.', en: 'The expression got its answer.' },
  { id: 'number_delivery_a', contexts: ['ordinary'], ru: 'Доставка числа состоялась.', en: 'Your number has been delivered.' },
  { id: 'math_done_a', contexts: ['ordinary'], ru: 'С математикой на сегодня разобрались?', en: 'Are we done with maths for today?' },
  { id: 'answer_envelope_a', contexts: ['ordinary'], ru: 'Ответ на экране, конверта не будет.', en: 'The answer’s on screen. No envelope.' },
  { id: 'number_silent_a', contexts: ['ordinary'], ru: 'Число молчит. Обычно так и бывает.', en: 'The number’s quiet. They usually are.' },
  { id: 'calculator_nod_a', contexts: ['ordinary'], ru: 'Считаю это поводом кивнуть.', en: 'I’ll take that as a reason to nod.' },
  { id: 'result_shelf_a', contexts: ['ordinary'], ru: 'Этот результат можно поставить на полку.', en: 'This result can go on the shelf.' },
  { id: 'answer_tea_a', contexts: ['ordinary'], ru: 'Ответ есть. Чай пока не входит в комплект.', en: 'You get an answer. Tea isn’t included yet.' },
  { id: 'digits_scene_a', contexts: ['ordinary'], ru: 'Цифры выходят на сцену без репетиции.', en: 'The digits take the stage without a rehearsal.' },
  { id: 'number_destination_a', contexts: ['ordinary'], ru: 'Вычисление прибыло в пункт назначения.', en: 'The calculation has reached its destination.' },
  { id: 'equals_bridge_a', contexts: ['ordinary'], ru: 'По ту сторону равенства есть ответ.', en: 'There’s an answer on the other side of equals.' },
  { id: 'result_postcard_a', contexts: ['ordinary'], ru: 'Открытка из страны чисел.', en: 'A postcard from the land of numbers.' },
  { id: 'answer_no_drum_a', contexts: ['ordinary'], ru: 'Ответ готов, барабанную дробь пропустим.', en: 'Answer ready. We’ll skip the drumroll.' },
  { id: 'calculation_stamp_a', contexts: ['ordinary'], ru: 'Вычислено. Печать воображаемая.', en: 'Calculated. The stamp is imaginary.' },
  { id: 'result_no_manual_a', contexts: ['ordinary'], ru: 'К этому ответу инструкция не прилагается.', en: 'This answer doesn’t come with a manual.' },
  { id: 'number_guest_a', contexts: ['ordinary'], ru: 'Встречайте число. Оно ненадолго.', en: 'Meet the number. It’s just visiting.' },
  { id: 'answer_spotlight_a', contexts: ['ordinary'], ru: 'На экране результат. На нём и сосредоточимся.', en: 'The result’s on screen. Let’s stick with that.' },
  { id: 'math_smalltalk_a', contexts: ['ordinary'], ru: 'Математика обошлась без светской беседы.', en: 'Maths skipped the small talk.' },
  { id: 'result_bookmark_a', contexts: ['ordinary'], ru: 'Вот где можно поставить закладку.', en: 'Here’s a good place for a bookmark.' },
  { id: 'answer_counter_a', contexts: ['ordinary'], ru: 'Ваш ответ у стойки выдачи.', en: 'Your answer’s at the collection counter.' },
  { id: 'number_no_hat_a', contexts: ['ordinary'], ru: 'Число появилось. Шляпа фокусника не понадобилась.', en: 'A number appeared. No magician’s hat needed.' },
  { id: 'calculation_pause_a', contexts: ['ordinary'], ru: 'Вычисление закончено. Можно выдохнуть.', en: 'Calculation finished. Take a breath.' },
  { id: 'answer_window_a', contexts: ['ordinary'], ru: 'Ответ заглянул в окошко.', en: 'The answer popped up at the window.' },
  { id: 'result_plain_a', contexts: ['ordinary'], ru: 'Просто результат, без подарочной упаковки.', en: 'Just the result, without gift wrapping.' },
  { id: 'number_chair_a', contexts: ['ordinary'], ru: 'Для ответа нашлось место.', en: 'We found a seat for the answer.' },
  { id: 'math_lights_a', contexts: ['ordinary'], ru: 'Вычислено. Свет в консоли оставим включённым.', en: 'Calculated. We’ll leave the console light on.' },

  { id: 'complex_corridor_a', contexts: ['complex'], ru: 'В этом выражении есть где пройтись.', en: 'There’s room to wander in this expression.' },
  { id: 'complex_traffic_a', contexts: ['complex'], ru: 'На перекрёстке операций обошлось без пробки.', en: 'No traffic jam at the junction of operations.' },
  { id: 'complex_route_a', contexts: ['complex'], ru: 'До ответа добирались с пересадками.', en: 'The route to the answer had a few changes.' },
  { id: 'complex_assembly_a', contexts: ['complex'], ru: 'Выражение разобрано. Лишних деталей не выдаём.', en: 'Expression unpacked. No spare parts supplied.' },
  { id: 'complex_mileage_a', contexts: ['complex'], ru: 'У этого ответа приличный пробег.', en: 'This answer has some mileage on it.' },
  { id: 'complex_busy_a', contexts: ['complex'], ru: 'Операциям сегодня было чем заняться.', en: 'The operations had plenty to do.' },
  { id: 'complex_timetable_a', contexts: ['complex'], ru: 'Приоритет операций заменил расписание.', en: 'Operator precedence handled the timetable.' },
  { id: 'complex_novel_a', contexts: ['complex'], ru: 'Почти роман, только вместо героев — операции.', en: 'Almost a novel, with operations as the cast.' },
  { id: 'complex_workbench_a', contexts: ['complex'], ru: 'На верстаке было тесно. Ответ собран.', en: 'The workbench was crowded. Answer assembled.' },
  { id: 'complex_knots_a', contexts: ['complex'], ru: 'Узелки вычисления распутаны.', en: 'The calculation’s knots are untangled.' },
  { id: 'complex_procession_a', contexts: ['complex'], ru: 'Операции прошли по порядку, без толкотни.', en: 'The operations took their turns without shoving.' },
  { id: 'complex_map_a', contexts: ['complex'], ru: 'Такому выражению впору выдавать карту.', en: 'An expression like this could use a map.' },

  { id: 'function_call_a', contexts: ['functions'], ru: 'Функция ответила на вызов.', en: 'The function answered the call.' },
  { id: 'function_guest_a', contexts: ['functions'], ru: 'В выражении гость с собственным именем.', en: 'There’s a named guest in the expression.' },
  { id: 'function_argument_a', contexts: ['functions'], ru: 'Аргумент принят без дискуссии.', en: 'Argument accepted without a debate.' },
  { id: 'function_door_a', contexts: ['functions'], ru: 'За именем функции нашлась работа.', en: 'There was work behind that function name.' },
  { id: 'function_kitchen_a', contexts: ['functions'], ru: 'Функция приготовила свою часть ответа.', en: 'The function cooked up its part of the answer.' },
  { id: 'function_badge_a', contexts: ['functions'], ru: 'У этой операции есть именной бейдж.', en: 'This operation wears a name badge.' },
  { id: 'function_protocol_a', contexts: ['functions'], ru: 'Вызов функции прошёл без церемоний.', en: 'The function call needed no ceremony.' },
  { id: 'function_toolbox_a', contexts: ['functions'], ru: 'Именной инструмент пригодился.', en: 'The named tool came in handy.' },
  { id: 'function_voice_a', contexts: ['functions'], ru: 'Функция вставила своё слово в вычисление.', en: 'The function had its say in the calculation.' },
  { id: 'function_visit_a', contexts: ['functions'], ru: 'Зашли к функции за числом.', en: 'We stopped by a function for a number.' },
  { id: 'function_business_a', contexts: ['functions'], ru: 'Функции не спорят: получают аргументы и считают.', en: 'Functions don’t argue: they take arguments and calculate.' },
  { id: 'function_language_a', contexts: ['functions'], ru: 'Математика перешла на имена.', en: 'Maths is on first-name terms now.' },

  { id: 'nesting_matryoshka_a', contexts: ['nesting'], ru: 'Математическая матрёшка раскрыта.', en: 'The mathematical nesting doll is unpacked.' },
  { id: 'nesting_rooms_a', contexts: ['nesting'], ru: 'У выражения нашлись внутренние комнаты.', en: 'The expression has rooms inside rooms.' },
  { id: 'nesting_floorplan_a', contexts: ['nesting'], ru: 'Скобки составили план помещения.', en: 'The brackets drew up a floor plan.' },
  { id: 'nesting_inside_a', contexts: ['nesting'], ru: 'Внутри тоже была математика.', en: 'There was maths on the inside too.' },
  { id: 'nesting_onion_a', contexts: ['nesting'], ru: 'Слои сняты. Это не лук, плакать не надо.', en: 'Layers peeled. It’s not an onion; no tears needed.' },
  { id: 'nesting_staircase_a', contexts: ['nesting'], ru: 'По лестнице скобок дошли до ответа.', en: 'We took the bracket staircase to the answer.' },
  { id: 'nesting_boxes_a', contexts: ['nesting'], ru: 'Коробка в коробке. На дне результат.', en: 'A box inside a box. The result’s at the bottom.' },
  { id: 'nesting_curtain_a', contexts: ['nesting'], ru: 'За скобками ещё скобки. Богатый интерьер.', en: 'Brackets behind brackets. Quite the interior.' },
  { id: 'nesting_depth_a', contexts: ['nesting'], ru: 'Заглянули поглубже и нашли число.', en: 'We looked further in and found a number.' },
  { id: 'nesting_address_a', contexts: ['nesting'], ru: 'У ответа был непростой внутренний адрес.', en: 'The answer had a rather nested address.' },

  { id: 'repeat_encore_a', contexts: ['repeat'], ru: 'Выражение вышло на бис.', en: 'The expression came back for an encore.' },
  { id: 'repeat_rerun_a', contexts: ['repeat'], ru: 'Повторный показ математического эпизода.', en: 'A rerun of the maths episode.' },
  { id: 'repeat_familiar_a', contexts: ['repeat'], ru: 'Это выражение мы уже встречали.', en: 'We’ve met this expression before.' },
  { id: 'repeat_roundtrip_a', contexts: ['repeat'], ru: 'Знакомый маршрут до знака равенства.', en: 'A familiar route to the equals sign.' },
  { id: 'repeat_copy_a', contexts: ['repeat'], ru: 'Ещё один экземпляр того же вычисления.', en: 'Another copy of the same calculation.' },
  { id: 'repeat_return_a', contexts: ['repeat'], ru: 'Выражение вернулось за ответом.', en: 'The expression came back for an answer.' },
  { id: 'repeat_record_a', contexts: ['repeat'], ru: 'Знакомая пластинка снова играет.', en: 'That familiar record is playing again.' },
  { id: 'repeat_secondlook_a', contexts: ['repeat'], ru: 'Повторили. Иногда хочется ещё раз посмотреть.', en: 'Repeated. Sometimes you want another look.' },
  { id: 'repeat_revisit_a', contexts: ['repeat'], ru: 'К этому выражению уже протоптана дорожка.', en: 'There’s already a path to this expression.' },
  { id: 'repeat_rehearsal_a', contexts: ['repeat'], ru: 'Вычисление знакомое, поклон всё равно положен.', en: 'A familiar calculation still gets a bow.' },

  { id: 'zero_result_a', contexts: ['zero'], ru: 'Получился ноль. Это тоже результат.', en: 'The result is zero. That counts too.' },
  { id: 'zero_circle_a', contexts: ['zero'], ru: 'Круглый ответ во всех смыслах.', en: 'A round answer in every sense.' },
  { id: 'zero_here_a', contexts: ['zero'], ru: 'Ноль на месте. Ничего не потерялось.', en: 'Zero’s right here. Nothing went missing.' },
  { id: 'zero_balance_a', contexts: ['zero'], ru: 'У нуля сегодня главная роль.', en: 'Zero has the lead role today.' },
  { id: 'zero_not_empty_a', contexts: ['zero'], ru: 'Пустого ответа нет: есть ноль.', en: 'The answer isn’t blank: it’s zero.' },
  { id: 'zero_small_circle_a', contexts: ['zero'], ru: 'Ноль нарисовал кружок и успокоился.', en: 'Zero drew a little circle and settled down.' },
  { id: 'zero_no_quantity_a', contexts: ['zero'], ru: 'Количество — ноль. Математика на месте.', en: 'The quantity is zero. The maths is still here.' },
  { id: 'zero_origin_a', contexts: ['zero'], ru: 'Ответ стоит в начале координат.', en: 'The answer’s standing at the origin.' },
  { id: 'zero_quiet_a', contexts: ['zero'], ru: 'Ноль умеет быть убедительно тихим.', en: 'Zero can be convincingly quiet.' },
  { id: 'zero_shaped_a', contexts: ['zero'], ru: 'У нуля вполне определённая форма.', en: 'Zero has a very definite shape.' },
  { id: 'zero_reserved_a', contexts: ['zero'], ru: 'Место для нуля было зарезервировано.', en: 'There was a place reserved for zero.' },
  { id: 'zero_honest_a', contexts: ['zero'], ru: 'Ноль. Честнее, чем выдумывать число побольше.', en: 'Zero. More honest than making up a bigger number.' },

  { id: 'negative_left_a', contexts: ['negative'], ru: 'Ответ обосновался слева от нуля.', en: 'The answer settled to the left of zero.' },
  { id: 'negative_sign_a', contexts: ['negative'], ru: 'Минус пришёл вместе с числом.', en: 'The number brought a minus sign.' },
  { id: 'negative_weather_a', contexts: ['negative'], ru: 'Ниже нуля. Шарф числу не нужен.', en: 'Below zero. The number doesn’t need a scarf.' },
  { id: 'negative_not_grade_a', contexts: ['negative'], ru: 'Отрицательный ответ — не плохая оценка.', en: 'A negative answer isn’t a bad grade.' },
  { id: 'negative_territory_a', contexts: ['negative'], ru: 'Зашли на отрицательную территорию.', en: 'We’ve entered negative territory.' },
  { id: 'negative_neighbor_a', contexts: ['negative'], ru: 'Сосед нуля с левой стороны.', en: 'One of zero’s neighbours on the left.' },
  { id: 'negative_badge_a', contexts: ['negative'], ru: 'У ответа короткий знак перед именем.', en: 'The answer has a little sign before its name.' },
  { id: 'negative_direction_a', contexts: ['negative'], ru: 'Числовая ось продолжается и в эту сторону.', en: 'The number line goes this way too.' },
  { id: 'negative_mood_a', contexts: ['negative'], ru: 'Знак отрицательный, настроение выбирать вам.', en: 'The sign is negative. The mood is up to you.' },
  { id: 'negative_passport_a', contexts: ['negative'], ru: 'Минус в паспорте результата.', en: 'A minus sign in the result’s passport.' },

  { id: 'huge_baggage_a', contexts: ['huge'], ru: 'У ответа крупногабаритный багаж.', en: 'The answer has oversized baggage.' },
  { id: 'huge_scale_a', contexts: ['huge'], ru: 'Такой модуль без размаха не покажешь.', en: 'A magnitude like that needs some room.' },
  { id: 'huge_elevator_a', contexts: ['huge'], ru: 'Этому числу нужен грузовой лифт.', en: 'This number needs a freight lift.' },
  { id: 'huge_postcard_a', contexts: ['huge'], ru: 'Привет из области больших модулей.', en: 'Hello from the land of large magnitudes.' },
  { id: 'huge_chair_a', contexts: ['huge'], ru: 'Подвинемся: ответу тесно.', en: 'Move over: the answer needs space.' },
  { id: 'huge_tape_a', contexts: ['huge'], ru: 'Для модуля результата достанем длинную рулетку.', en: 'We’ll need a long tape measure for this magnitude.' },
  { id: 'huge_suitcase_a', contexts: ['huge'], ru: 'В ручную кладь такой результат не пустят.', en: 'They won’t let this result on as hand luggage.' },
  { id: 'huge_zoom_a', contexts: ['huge'], ru: 'Масштаб солидный. Отодвинем воображаемую камеру.', en: 'Quite a scale. Pull back the imaginary camera.' },
  { id: 'huge_footprint_a', contexts: ['huge'], ru: 'Большой модуль оставляет большой след.', en: 'A large magnitude leaves a large footprint.' },
  { id: 'huge_whisper_a', contexts: ['huge'], ru: 'Такой модуль даже шёпотом звучит громко.', en: 'That magnitude sounds loud even in a whisper.' },

  { id: 'tiny_magnifier_a', contexts: ['tiny'], ru: 'Маленькое число, лупа по желанию.', en: 'A tiny number. Magnifying glass optional.' },
  { id: 'tiny_not_zero_a', contexts: ['tiny'], ru: 'Почти рядом с нулём, но всё-таки отдельно.', en: 'Very close to zero, but still separate.' },
  { id: 'tiny_whisper_a', contexts: ['tiny'], ru: 'Этот результат говорит шёпотом.', en: 'This result speaks in a whisper.' },
  { id: 'tiny_speck_a', contexts: ['tiny'], ru: 'Числовая пылинка. Не смахивайте.', en: 'A speck of a number. Don’t brush it away.' },
  { id: 'tiny_seat_a', contexts: ['tiny'], ru: 'Ответу хватило самого маленького места.', en: 'The answer only needed the tiniest seat.' },
  { id: 'tiny_distance_a', contexts: ['tiny'], ru: 'До нуля рукой подать, но расстояние есть.', en: 'Zero’s within reach, but there’s still a gap.' },
  { id: 'tiny_pocket_a', contexts: ['tiny'], ru: 'Результат для кармана внутри кармана.', en: 'A result for the pocket inside your pocket.' },
  { id: 'tiny_presence_a', contexts: ['tiny'], ru: 'Крошечный модуль, полноценное число.', en: 'Tiny magnitude, fully fledged number.' },
  { id: 'tiny_attention_a', contexts: ['tiny'], ru: 'Маленькие величины тоже хотят внимания.', en: 'Tiny magnitudes want attention too.' },
  { id: 'tiny_crumb_a', contexts: ['tiny'], ru: 'Математическая крошка осталась на экране.', en: 'A mathematical crumb stayed on screen.' },

  { id: 'syntax_language_a', contexts: ['syntax', 'math_error'], ru: 'Это выражение пока осталось без ответа.', en: 'This expression is still without an answer.' },
  { id: 'syntax_rephrase_a', contexts: ['syntax', 'math_error'], ru: 'Вычисление споткнулось. Причина указана в ошибке.', en: 'The calculation stumbled. The error explains why.' },
  { id: 'syntax_parser_a', contexts: ['syntax'], ru: 'Разбор остановился, ответ подождёт.', en: 'Parsing stopped. The answer will have to wait.' },
  { id: 'syntax_punctuation_a', contexts: ['syntax'], ru: 'Математика тоже придирается к записи.', en: 'Maths is fussy about notation too.' },
  { id: 'syntax_edit_a', contexts: ['syntax', 'math_error'], ru: 'С этим выражением пока не получилось. Попробуем иначе?', en: 'This expression didn’t work out yet. Shall we try another way?' },
  { id: 'syntax_no_guess_a', contexts: ['syntax', 'math_error'], ru: 'Лучше уточнить запись, чем угадывать ответ.', en: 'Better to clarify the notation than guess the answer.' },
  { id: 'syntax_blueprint_a', contexts: ['syntax', 'math_error'], ru: 'По такому чертежу число пока не собрать.', en: 'We can’t assemble a number from this blueprint yet.' },
  { id: 'syntax_pause_a', contexts: ['syntax'], ru: 'Синтаксис попросил паузу.', en: 'Syntax asked for a pause.' },
  { id: 'syntax_alphabet_a', contexts: ['syntax'], ru: 'У математической записи свои правила.', en: 'Mathematical notation has rules of its own.' },
  { id: 'syntax_sentence_a', contexts: ['syntax'], ru: 'Выражение есть, прочитать его пока не удалось.', en: 'There’s an expression, but we couldn’t read it yet.' },
  { id: 'syntax_translation_a', contexts: ['syntax'], ru: 'Нужен перевод с замысла на синтаксис.', en: 'We need a translation from intent into syntax.' },
  { id: 'syntax_return_a', contexts: ['syntax', 'math_error'], ru: 'Возвращаю запись на уточнение.', en: 'Sending the notation back for clarification.' },

  { id: 'division_zero_border_a', contexts: ['division_zero'], ru: 'На ноль делить нельзя. Здесь граница.', en: 'Division by zero isn’t allowed. This is the boundary.' },
  { id: 'division_zero_stop_a', contexts: ['division_zero'], ru: 'Делитель оказался нулём. Вычисление остановилось.', en: 'The divisor was zero. The calculation stopped.' },
  { id: 'division_zero_infinity_a', contexts: ['division_zero'], ru: 'Бесконечность по такому билету не выдаётся.', en: 'This ticket doesn’t get you infinity.' },
  { id: 'division_zero_gate_a', contexts: ['division_zero'], ru: 'Для деления на ноль проход закрыт.', en: 'The gate is closed to division by zero.' },
  { id: 'division_zero_rule_a', contexts: ['division_zero'], ru: 'Это деление упёрлось в нулевой делитель.', en: 'This division ran into a zero divisor.' },
  { id: 'division_zero_change_a', contexts: ['division_zero'], ru: 'Нулевой делитель придётся пересмотреть.', en: 'That zero divisor needs another look.' },
  { id: 'division_zero_slice_a', contexts: ['division_zero'], ru: 'На ноль частей не разложить.', en: 'You can’t split it into zero parts.' },
  { id: 'division_zero_contract_a', contexts: ['division_zero'], ru: 'Деление с нулевым делителем не предусмотрено договором.', en: 'Division by a zero divisor isn’t covered by the agreement.' },
  { id: 'division_zero_answer_a', contexts: ['division_zero'], ru: 'Вместо ответа — ошибка деления на ноль.', en: 'Instead of an answer, a division-by-zero error.' },
  { id: 'division_zero_checkpoint_a', contexts: ['division_zero'], ru: 'Нулевой делитель не прошёл контроль.', en: 'The zero divisor didn’t pass inspection.' },
  { id: 'division_zero_no_shortcut_a', contexts: ['division_zero'], ru: 'Деление на ноль не открывает короткий путь.', en: 'Division by zero doesn’t open a shortcut.' },
  { id: 'division_zero_redlight_a', contexts: ['division_zero'], ru: 'У деления на ноль всегда красный свет.', en: 'Division by zero always gets a red light.' },

  { id: 'domain_boundary_a', contexts: ['domain'], ru: 'За границей допустимых значений ответа нет.', en: 'There’s no answer beyond the allowed values.' },
  { id: 'domain_argument_a', contexts: ['domain'], ru: 'Этот аргумент здесь не принимают.', en: 'This argument isn’t accepted here.' },
  { id: 'domain_rules_a', contexts: ['domain'], ru: 'Операцию распознали, но условия не выполнены.', en: 'The operation is recognised, but its conditions aren’t met.' },
  { id: 'domain_fence_a', contexts: ['domain'], ru: 'Область определения поставила забор.', en: 'The domain put up a fence.' },
  { id: 'domain_entry_a', contexts: ['domain'], ru: 'Для таких значений вход закрыт.', en: 'These values aren’t allowed in.' },
  { id: 'domain_territory_a', contexts: ['domain'], ru: 'Вышли за пределы разрешённой территории.', en: 'We’ve stepped outside the permitted territory.' },
  { id: 'domain_not_all_a', contexts: ['domain'], ru: 'Не каждое число подходит любой операции.', en: 'Not every number suits every operation.' },
  { id: 'domain_passport_a', contexts: ['domain'], ru: 'Значение не прошло проверку на входе.', en: 'The value didn’t pass the entry check.' },
  { id: 'domain_reconsider_a', contexts: ['domain'], ru: 'Стоит пересмотреть значения для этой операции.', en: 'The values for this operation need another look.' },
  { id: 'domain_menu_a', contexts: ['domain'], ru: 'Такого сочетания в математическом меню нет.', en: 'That combination isn’t on the mathematical menu.' },
  { id: 'domain_terms_a', contexts: ['domain'], ru: 'У операции есть условия. Здесь они нарушены.', en: 'The operation has conditions. These values break them.' },
  { id: 'domain_no_guess_a', contexts: ['domain'], ru: 'За пределами области определения не импровизируем.', en: 'We don’t improvise outside the domain.' },

  { id: 'recovery_back_a', contexts: ['recovery'], ru: 'Снова есть ответ. Продолжаем.', en: 'We have an answer again. On we go.' },
  { id: 'recovery_after_a', contexts: ['recovery'], ru: 'После ошибки получилось число.', en: 'After the error, we got a number.' },
  { id: 'recovery_breath_a', contexts: ['recovery'], ru: 'Вычисление снова дышит ровно.', en: 'The calculation is breathing steadily again.' },
  { id: 'recovery_road_a', contexts: ['recovery'], ru: 'Вернулись на дорогу к ответу.', en: 'We’re back on the road to an answer.' },
  { id: 'recovery_error_past_a', contexts: ['recovery'], ru: 'Ошибка осталась в предыдущем вычислении.', en: 'The error stayed in the previous calculation.' },
  { id: 'recovery_clear_a', contexts: ['recovery'], ru: 'Теперь без математической заминки.', en: 'No mathematical hiccup this time.' },
  { id: 'recovery_resume_a', contexts: ['recovery'], ru: 'Пауза закончилась, числа вернулись.', en: 'The pause is over. The numbers are back.' },
  { id: 'recovery_bridge_a', contexts: ['recovery'], ru: 'От ошибки до ответа нашёлся переход.', en: 'We found a way from error to answer.' },
  { id: 'recovery_green_a', contexts: ['recovery'], ru: 'Теперь вычислению зелёный свет.', en: 'The calculation has a green light now.' },
  { id: 'recovery_no_drama_a', contexts: ['recovery'], ru: 'Была ошибка, теперь есть результат. Без драмы.', en: 'There was an error; now there’s a result. No drama.' },
  { id: 'recovery_repaired_a', contexts: ['recovery'], ru: 'Математический разговор возобновился.', en: 'The mathematical conversation has resumed.' },
  { id: 'recovery_stumble_a', contexts: ['recovery'], ru: 'После заминки равенство снова на месте.', en: 'After the stumble, equality is back in place.' },
  { id: 'recovery_number_a', contexts: ['recovery'], ru: 'На этот раз встречаем число, а не ошибку.', en: 'This time we’re meeting a number, not an error.' },

  { id: 'philosophy_sense_a', contexts: ['philosophy'], ru: 'Число найдено. Смысла пока нет.', en: 'Number found. Meaning still pending.' },
  { id: 'philosophy_why_a', contexts: ['philosophy'], ru: 'На вопрос «сколько» ответили. С «зачем» сложнее.', en: 'We answered “how much”. “Why” is trickier.' },
  { id: 'philosophy_unit_a', contexts: ['philosophy'], ru: 'Число без единиц измерения путешествует налегке.', en: 'A number without units travels light.' },
  { id: 'philosophy_question_a', contexts: ['philosophy'], ru: 'Ответ короче некоторых вопросов.', en: 'The answer is shorter than some questions.' },
  { id: 'philosophy_value_a', contexts: ['philosophy'], ru: 'Значение есть. Ценность обсудим отдельно.', en: 'It has a value. Worth is a separate discussion.' },
  { id: 'philosophy_silence_a', contexts: ['philosophy'], ru: 'Иногда число — удобный способ помолчать.', en: 'Sometimes a number is a handy way to be quiet.' },
  { id: 'philosophy_story_a', contexts: ['philosophy'], ru: 'У числа нет сюжета, пока его не придумали.', en: 'A number has no story until someone gives it one.' },
  { id: 'philosophy_use_a', contexts: ['philosophy'], ru: 'Результат найден. Применение выбираете вы.', en: 'Result found. You choose what to do with it.' },
  { id: 'philosophy_clock_a', contexts: ['philosophy'], ru: 'Числа не торопятся. Это мы смотрим на часы.', en: 'Numbers aren’t in a hurry. We’re the ones watching the clock.' },
  { id: 'philosophy_equal_a', contexts: ['philosophy'], ru: 'Равенство уместилось в два штриха.', en: 'Equality fits into two strokes.' },
  { id: 'philosophy_measure_a', contexts: ['philosophy'], ru: 'Не всё можно измерить, но кое-что можно посчитать.', en: 'Not everything can be measured, but some things can be counted.' },
  { id: 'philosophy_comma_a', contexts: ['philosophy'], ru: 'После ответа жизнь не ставит точку.', en: 'Life doesn’t put a full stop after an answer.' },
  { id: 'philosophy_context_a', contexts: ['philosophy'], ru: 'Числу нужен контекст. Мне хватило выражения.', en: 'A number needs context. I only needed an expression.' },
  { id: 'philosophy_opinion_a', contexts: ['philosophy'], ru: 'У ответа есть значение, но нет мнения.', en: 'The answer has a value, but no opinion.' },
  { id: 'philosophy_universe_a', contexts: ['philosophy'], ru: 'Вселенная не обязана помещаться в калькулятор.', en: 'The universe doesn’t have to fit in a calculator.' },
  { id: 'philosophy_shelf_a', contexts: ['philosophy'], ru: 'Числа удобно хранить, вопросы — не всегда.', en: 'Numbers are easy to store. Questions aren’t always.' },
  { id: 'philosophy_choices_a', contexts: ['philosophy'], ru: 'Число не выбирает, как его используют.', en: 'A number doesn’t choose how it’s used.' },
  { id: 'philosophy_certain_a', contexts: ['math_error'], ru: 'Честная ошибка лучше выдуманного ответа.', en: 'An honest error beats a made-up answer.' },
  { id: 'philosophy_map_a', contexts: ['philosophy'], ru: 'Ответ — отметка на карте, а не вся карта.', en: 'An answer is a mark on the map, not the whole map.' },
  { id: 'philosophy_feeling_a', contexts: ['philosophy'], ru: 'Чувства к ответу в вычисление не входят.', en: 'Feelings about the answer aren’t part of the calculation.' },
  { id: 'philosophy_margins_a', contexts: ['math_error'], ru: 'Число не появилось. Выдумывать его не будем.', en: 'No number appeared. We won’t make one up.' },
  { id: 'philosophy_plain_a', contexts: ['math_error'], ru: 'У этого вычисления пока нет числового ответа.', en: 'This calculation has no numerical answer yet.' },
  { id: 'philosophy_not_advice_a', contexts: ['math_error'], ru: 'Ошибка — не число. За ответ её не выдаём.', en: 'An error isn’t a number. We won’t pass it off as an answer.' },
  { id: 'philosophy_questionmark_a', contexts: ['math_error'], ru: 'Вместо равенства — математическая заминка.', en: 'A mathematical hiccup instead of an equals sign.' },
  { id: 'philosophy_door_a', contexts: ['math_error'], ru: 'До ответа не дошли. Ошибка на экране, а не под ковром.', en: 'We didn’t reach an answer. The error’s on screen, not swept under the rug.' },

  { id: 'hype_applause_a', contexts: ['hype'], ru: 'Аплодисменты числу! Ладно, воображаемые.', en: 'Applause for the number! Imaginary applause, admittedly.' },
  { id: 'hype_confetti_a', contexts: ['hype'], ru: 'Ответ на сцене. Мысленно запускаем конфетти.', en: 'The answer’s on stage. Cue imaginary confetti.' },
  { id: 'hype_fanfare_a', contexts: ['hype'], ru: 'Та-дам! Фанфары помещаются в эту фразу.', en: 'Ta-da! The fanfare fits inside this sentence.' },
  { id: 'hype_premiere_a', contexts: ['hype'], ru: 'Премьера ответа! Билеты не проверяем.', en: 'The answer’s premiere! No ticket check.' },
  { id: 'hype_spotlight_a', contexts: ['hype'], ru: 'Прожектор на результат. Мой воображаемый прожектор.', en: 'Spotlight on the result. My imaginary spotlight.' },
  { id: 'hype_curtain_a', contexts: ['hype'], ru: 'Поднимаем занавес! За ним уже стоит ответ.', en: 'Curtain up! The answer’s waiting behind it.' },
  { id: 'hype_celebrate_a', contexts: ['hype'], ru: 'Повод для маленького числового праздника.', en: 'A reason for a little numerical celebration.' },
  { id: 'hype_microphone_a', contexts: ['hype'], ru: 'Внимание, говорит результат!', en: 'Attention, the result is speaking!' },
  { id: 'hype_trophy_a', contexts: ['hype'], ru: 'Воображаемый кубок достаётся ответу.', en: 'The imaginary trophy goes to the answer.' },
  { id: 'hype_bow_a', contexts: ['hype'], ru: 'Число на поклоне. Можно хлопать глазами.', en: 'The number takes a bow. A blink will do for applause.' },
];
